### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by MortenL** [patrickdemooij9/SimpleRedirects#11]
Hi,

I'm getting a "Could not install package 'SimpleRedirects 1.0.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." error when trying to install.

Is there something missing in the newest package? - I've previously installed 1.0.8 on projects without problems.

**Comment by patrickdemooij9** [comment]
Hi @MortenL,
Hmm, that is strange. The latest update only changes some code related to the caching. I'll see if I can reproduce it!

**Comment by patrickdemooij9** [comment]
Hi @MortenL,
I've been able to reproduce the issue. I am not quite sure where it came from, but it seems like it was building for .NETFramework 4.5.2 (probably something left over from the previous package). I've updated it now. Could you see if installing version 1.0.10 gives you any issues?

**Comment by MortenL** [comment]
Yeah, that worked perfectly - thank you very much!
