### ISSUE TITLE
Testing clicking redirect in backoffice, does not use website URL

### ISSUE THREAD

**Issue by JacobBertelsen** [patrickdemooij9/SimpleRedirects#13]
When using a different URL for backoffice and website:
backoffice.example.com for backoffice
www.example.com for the website,
clicking a redirect in the SimpleRedirectManager to test it, points to [old-path].backoffice.example.com , instead of [old-path].www.example.com .

I assume wanted behaviour is that the link that opens, goes to the website url, with the old path we want redirected, pre-pended.

**Comment by patrickdemooij9** [comment]
Hi @JacobBertelsen,

Thanks for the issue report, I'll take a look at what I can do.
The only question that I have is how you can set up a different domain for your backoffice. Are you load-balancing it? (Sorry, never actually moved the backoffice to a different domain)

**Comment by JacobBertelsen** [comment]
Hi @patrickdemooij9 ,
I misunderstood something in our implementation, so the issue appearantly does not reside within SimpleRedirectManager.
Thanks for your quick response, regardless :)
