### ISSUE TITLE
Installing of package cause my CMS to hit error 

### ISSUE THREAD

**Issue by Riadenx3m** [patrickdemooij9/SimpleRedirects#14]
Hi,

After uploading the package "Simple 301 redirect" into umbraco 8, now I cannot go into the back office of my cms. 

How do I remove the package from my CMS.

Please assist as we are going to production in a few days time

**Comment by patrickdemooij9** [comment]
Hi @Riadenx3m,

If you downloaded "Simple 301 redirect" for Umbraco 8, it'll not work. "Simple 301 redirect" has no v8 version. SimpleRedirects (this repository) is a v8 of that package.

For how to delete it, it depends on how you added the package on the website.

**If you added the package through Nuget:**
You should be able to simply uninstall the Nuget package in the nuget package manager. It might be that some files from the app_plugins/simple301 are still there after uninstall, so you might have to remove them by hand.

**If you added the package through our.umbraco.org or the backoffice (packages tab):**
This would be a bit more difficult as you aren't able to access the CMS anymore. But you'll want to delete the following folder: /App_Plugins/Simple301. After deleting that, you might have to restart your server, but you should be able to access the CMS again.

Let me know if this helps you!

With kind regards,
Patrick

**Comment by Riadenx3m** [comment]
Hi Patrick,

Thanks for the help.

After deleting the file and restarting the server still have this error.

Message:
"Boot failed." (861ms) [Timing "21d137d"]

									
Exception:
Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Simple301, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Persistence.Migrations.MigrationBase: Could not load type 'Umbraco.Core.Persistence.Migrations.MigrationBase' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.5780.28255, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.TypeLoadException on Umbraco.Core.ApplicationEventHandler: Could not load type 'Umbraco.Core.ApplicationEventHandler' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.5780.28255, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Core.Composing.TypeFinder.FindClassesOfType[T](IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass53_0`1.<GetTypes>b__1()
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Core.Runtime.CoreRuntime.GetComposerTypes(TypeLoader typeLoader)
   at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader)
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)
   --- End of inner exception stack trace ---

**Comment by Riadenx3m** [comment]
btw I deleted using /App_Plugins/Simple301

**Comment by patrickdemooij9** [comment]
@Riadenx3m,

Could you check the /bin folder if there is anything there related to Simple301? I think that there is still a Simple301.dll there somewhere judging from the error.

**Comment by Riadenx3m** [comment]
Hi Patrick,

After deleting from the bin folder, I am able to access my back office. Thanks alot for the help.

Any recommendation for packages for url redirect in umbraco 8 ?

**Comment by patrickdemooij9** [comment]
Hi @Riadenx3m ,

You can use SimpleRedirects. It's the same redirect package that you tried to download, but it is the Umbraco 8 version.

**Comment by Riadenx3m** [comment]
Hi Patrick,

I have installed the SimpleRedirect Package but nothing happen. I Navigated to the Umbraco > Content section, i dont see any Manage Redirects' tab. our current tab did not allow us to add any url but only remove it. I have attached an image.

![Capture1](https://user-images.githubusercontent.com/86480758/123531472-85080300-d737-11eb-96a6-488aa81bf4cd.PNG)


I attached an image of the SimpleRedirect package that I installed. 
![Capture2](https://user-images.githubusercontent.com/86480758/123531540-f21b9880-d737-11eb-906c-b5b572aaa72d.PNG)

I attached an image inside our webconfig 
![image](https://user-images.githubusercontent.com/86480758/123531591-6f470d80-d738-11eb-96c6-a01075ddfd36.png)

**Comment by patrickdemooij9** [comment]
Interesting.. I'll take a look at what is going wrong.
Another redirects module that you could use is https://our.umbraco.com/packages/website-utilities/skybrud-redirects/

**Comment by patrickdemooij9** [comment]
Hi @Riadenx3m,
I just updated the version of SimpleRedirects. If you install the package again (You might have to uninstall the current version first), then it should work!

**Comment by Riadenx3m** [comment]
let me  try

**Comment by Riadenx3m** [comment]
Looks like it is working fine now. 

Thanks for your help
