### ISSUE TITLE
Option to have redirects ignore querystrings

### ISSUE THREAD

**Issue by patrickdemooij9** [patrickdemooij9/SimpleRedirects#18]
Currently if you have a redirect like this: /oldUrl -> /newUrl.
It will only trigger the redirect if you go to /oldUrl. If you put any query strings behind it like /oldUrl?utm_source=google, it'll not find the redirect. 
Due to this changing the current functionality which people might be depending on, we should make it a configuration option, so that people have the ability to turn it off.

**Comment by StuartPaterson** [comment]
Hey Patrick,

I'm currently running an Umbraco 8.18 site with SimpleRedirects 1.0.11 installed and looks like this might be an issue for us.  Basically we have a load of campaign landing pages.  When a visitor gets a link to one of these pages it contains a query string and this is being lost during a 301 redirect.

Was this solution ever something you had in beta or was it only being looked in to for Umbraco V9/10?

Thanks,
Stuart

**Comment by patrickdemooij9** [comment]
Hi @StuartPaterson,

I haven't had the time to look into this functionality yet, but I can take a look at it. But what you would like is that if someone comes to an URL like /page?param=1, that he would then get redirected to /redirected-page?param=1 right? How are your redirects currently setup?

**Comment by StuartPaterson** [comment]
Hi Patrick,

That's exactly it...we have a large volume of pages which now have a difference parent node name so within Simple Redirects we've added a load of redirects in the format -   /landing-pages/pageName redirected to /lp/pageName

Basically these pages are used for PPC and campaigns so anyone visiting these pages usually has some form of tracking query string appended to the URL like this - 

?utm_source=twitter&utm_medium=social&utm_campaign=twitterrealstoryAAT

So yeah at the moment we're not getting that tracking information as the redirect drops it.

**Comment by patrickdemooij9** [comment]
Oke, I'll see what I can do for you this weekend. I was planning to stop working on the v8 package, but this doesn't seem like such a big change

**Comment by StuartPaterson** [comment]
That's great, thanks a lot Patrick...I'm not sure how else we would solve this one otherwise other than going for some other re-write package, but we use Simple Redirects across a few sites so it would be a great solution for us.

**Comment by StuartPaterson** [comment]
Hey Patrick,

Sorry to follow up so soon but obviously have some pressure to resolve this problem we have...is there anything I could try and take a look at do you think?

Thanks,
Stuart

**Comment by patrickdemooij9** [comment]
Hi @StuartPaterson,

Sorry for the delay, but I've got an update ready for this. The update is available in this version [1.0.11-beta1](https://www.nuget.org/packages/SimpleRedirects/1.0.11-beta1) (It should have been 1.1.0-beta1, but I messed that one up).

This adds 2 new settings that you'll have to add to your web.config as this isn't enabled by default.
```
<add key="SimpleRedirects.IgnoreQueryString" value="true" />
<add key="SimpleRedirects.PreserveQueryString" value="true" />
```

SimpleRedirects.IgnoreQueryString allows redirects to match without their querystring. So if you have a redirect from /test1 to /test2. It'll also redirect when visiting /test1?testParam=true

SimpleRedirects.PreserveQueryString preserves the original querystring. So in the top example, it would redirect to /test2?testParam=true.

Please see if this is what you want! If it is all good, I'll push this to an 1.1.0 version.

**Comment by StuartPaterson** [comment]
Hey Patrick, Yeah!!!!!!

You've made some people very happy this morning haha...thank you so much for putting in the time and effort to get this update together for us, really appreciate it.  The update works like a charm.

Owe you beer or two if our paths should be meet at some Umbraco Festival in the future!

Cheers,
Stuart

**Comment by patrickdemooij9** [comment]
Great to hear! I'll merge this functionality to the Umbraco 9,10 versions and then release an official version for it. Although, you can also just use beta version for the time being
