### ISSUE TITLE
Media File redirects?

### ISSUE THREAD

**Issue by ghost** [patrickdemooij9/SimpleRedirects#19]
Just wondering if this package supports media file redirects, e.g.:

/media/xxx/somefile.png -> /media/abc/someotherfile.png

Thanks!

**Comment by patrickdemooij9** [comment]
Hi @rbproworks,
The package currently doesn't support media file redirects. It is however something that'll be added later on!

**Comment by ricardojlp** [comment]
Hi @patrickdemooij9  ,
When do you expect to have the media file redirect available?

**Comment by patrickdemooij9** [comment]
Hi @ricardojlp,
Good question! I haven't had the time to work on it yet, but I'll take a look at it this week to see how much work this would be. I'll keep you posted!

**Comment by ricardojlp** [comment]
> Hi @ricardojlp, Good question! I haven't had the time to work on it yet, but I'll take a look at it this week to see how much work this would be. I'll keep you posted!

Hi @patrickdemooij9,
Any update on this matter?

**Comment by patrickdemooij9** [comment]
Hi @ricardojlp,
Sorry for the late reply. I have a PR now open that'll include this functionality. I'll probably merge it in the coming days and then create a new version for it.

**Comment by patrickdemooij9** [comment]
@rbproworks & @ricardojlp,
This feature can now be found in the latest version (2.1.0). Let me know if you encounter any issues!

**Comment by ricardojlp** [comment]
Hi @patrickdemooij9 ,
This latest version (2.1.0) is for Umbraco v9 only, correct? Can we have this fix for Umbraco V8 too?

**Comment by patrickdemooij9** [comment]
@ricardojlp,
Yeah, 2.1.0 is only for Umbraco 9. I'll see what I can do for the v8 version

**Comment by patrickdemooij9** [comment]
Hi @ricardojlp,

Sorry for the late reply, but I've had a look at the v8 version and it will have a big impact on the package if I were to add the media file redirects there as well. Along with Net Core being the newest version, I am sorry to say that I won't be developing this functionality for the v8 version.

If you do think that there is a good way of doing this, then you are able to make a PR for it and we can then discuss on how to move forward.
