### ISSUE TITLE
Redirect from a URL that contains a '+' doesn't work

### ISSUE THREAD

**Issue by ricardojlp** [patrickdemooij9/SimpleRedirects#22]
Redirecting from an "/old+url" doesn't work because of the plus sign.

**Comment by patrickdemooij9** [comment]
Hi @ricardojlp,
Thanks for the report. I'll take a look to see if I can reproduce it and will then fix it.

**Comment by patrickdemooij9** [comment]
Hi @ricardojlp,
Are you experiencing this on Umbraco 9 or Umbraco 8?

I tried this on my Umbraco 9 test site (running with dotnet run) and that works perfectly. However, if I try to run the website with IIS, then I'll get the following error:
![image](https://user-images.githubusercontent.com/11466511/156789381-fa617fd6-be63-4198-aa48-0bcb529cd537.png)

This is something that is done by IIS to prevent SQL injections and there is no way for SimpleRedirects to prevent it. If you turn it off, then I am sure that SimpleRedirects will correctly redirect you (https://stackoverflow.com/questions/66654411/how-to-enable-double-escaping-in-net-core-webapi). However, it is not advised to turn this security feature off.

I haven't tested this on a v8 site yet, but I think this will have the same issue if it is running with IIS.

**Comment by patrickdemooij9** [comment]
As this issue is now a few months old without any reply, I'll be closing the issue. Feel free to reopen it if this is still relevant.
