### ISSUE TITLE
Caching in distributed setup

### ISSUE THREAD

**Issue by rosrosros** [patrickdemooij9/SimpleRedirects#24]
Thanks for a great package!

We have a setup with a backoffice server and a frontend server.
It seems editing or deleting a redirect on the backoffice server does not flush the memory cache on the frontend server.
On the frontend server we must rely on `settings.CacheDuration` to expire the cache

Does that seem correct?
Is there any plans on supporting flush in multi server setup?

**Comment by patrickdemooij9** [comment]
Hi @rosrosros,

SimpleRedirects indeed hasn't been fully build with multiple servers in mind, but I think this should be an easy fix. I'll make sure to check it out this week and keep you updated!

What Umbraco version are you currently using?

**Comment by rosrosros** [comment]
Thats just perfect - thanks for responding so quickly.

We are on umbraco 9.4.1

Let me know if you need any help regarding this issue

**Comment by rosrosros** [comment]
Hi @patrickdemooij9 
Did you have a chance to look at this one yes?

Do you need any help?

**Comment by patrickdemooij9** [comment]
Hi @rosrosros,

Sorry about the late reply, the week was a bit busier than expected! But I managed to fix this today. It should now clear the cache on all the other servers as well. Would you be able to download the latest version (2.2.0) and confirm that this is now also the case for you?

**Comment by rosrosros** [comment]
Hi @patrickdemooij9 
It works like a charm - thanks for the swift response
