### ISSUE TITLE
Umbraco 9/10 unable to process SimpleRedirects CSS

### ISSUE THREAD

**Issue by kdx-perbol** [patrickdemooij9/SimpleRedirects#26]
After installing SimpleRedirects in our Umbraco 9 solution, Smidge is not able to process the backoffice CSS. 

This appears in the logs:

> System.InvalidOperationException: Expected expression, found '',Expected expression, found '' at Smidge.Nuglify.NuglifyCss.ProcessAsync(...) ... at Smidge.FileProcessors.CssImportProcessor.ProcessAsync

Problem only appears when Smidge is enabled, i.e. in non-debug/non-development.

Replacing the SimpleRedirects CSS files with empty/minimal contents removes the error.

Tested on Umbraco 9.5 and 10.1.

Not sure if the problem appears in a minimal reproduction or just in our solution. Not sure how to test a minimal repro in production mode with Smidge.

**Comment by patrickdemooij9** [comment]
Hi @kdx-perbol

Thanks for the report. We do have production websites running with SimpleRedirects, so I am not quite sure where it is coming from. Are there any specific Smidge settings that you are using? And what version of SimpleRedirects are you running?

**Comment by kdx-perbol** [comment]
Using SimpleRedirects version 3.0.0.

The only Smidge configuration is this:

```
  "smidge": {
    "dataFolder": "Smidge",
    "version": "16"
  },

```

These look like defaults so I'm not sure why they're in there. Likely inherited from Umbraco 8.

We use Smidge for our own custom front-end bundles as well, no problems there.

I have to say though, the `styles.css` does look kind of strange in places. When running it through W3C Jigsaw there are 13 errors:

```
1689 |   | Value Error : margin-top Too many values or values are not recognized : 1px \9
3066 |   | Deprecated media feature max-device-width. For guidance, see the Deprecated Media Features section in the current Media Queries specification.
4803 |   | Value Error : border-top-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-top-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
4824 |   | Value Error : border-right-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-right-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
4836 |   | Value Error : border-bottom-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-bottom-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
4852 |   | Value Error : border-left-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-left-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
4889 |   | only 0 can be a unit. You must put a unit after your number : 1000
4958 |   | Missing a semicolon before the property name progid
4958 |   | Property progid doesn't exist : DXImageTransform
4959 |   | Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1) }
4967 |   | Missing a semicolon before the property name progid
4967 |   | Property progid doesn't exist : DXImageTransform
4968 |   | Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1) }


```

**Comment by patrickdemooij9** [comment]
> Using SimpleRedirects version 3.0.0.
> 
> The only Smidge configuration is this:
> 
> ```
>   "smidge": {
>     "dataFolder": "Smidge",
>     "version": "16"
>   },
> ```
> 
> These look like defaults so I'm not sure why they're in there. Likely inherited from Umbraco 8.
> 
> We use Smidge for our own custom front-end bundles as well, no problems there.
> 
> I have to say though, the `styles.css` does look kind of strange in places. When running it through W3C Jigsaw there are 13 errors:
> 
> ```
> 1689 |   | Value Error : margin-top Too many values or values are not recognized : 1px \9
> 3066 |   | Deprecated media feature max-device-width. For guidance, see the Deprecated Media Features section in the current Media Queries specification.
> 4803 |   | Value Error : border-top-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-top-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
> 4824 |   | Value Error : border-right-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-right-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
> 4836 |   | Value Error : border-bottom-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-bottom-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
> 4852 |   | Value Error : border-left-color fadein(rgb(0, 0, 0, 0.2),7.5%) is not a border-left-color value : fadein(rgb(0, 0, 0, 0.2),7.5%)
> 4889 |   | only 0 can be a unit. You must put a unit after your number : 1000
> 4958 |   | Missing a semicolon before the property name progid
> 4958 |   | Property progid doesn't exist : DXImageTransform
> 4959 |   | Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1) }
> 4967 |   | Missing a semicolon before the property name progid
> 4967 |   | Property progid doesn't exist : DXImageTransform
> 4968 |   | Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1) }
> ```

Yeah, most of the styling in the .css file isn't being used and was copied over from the original project. I'll see how much of the .css I can throw away and see if that'll help with the issue.

**Comment by patrickdemooij9** [comment]
Hi @kdx-perbol 
I just released version 3.1.0 (Umbraco v10) where I managed to get rid of a lot of CSS lines. I wasn't able to reproduce the issue, so I hope that this will fix the issue for you.

**Comment by kdx-perbol** [comment]
> version 3.1.0 (Umbraco v10) 

Thank you. I will try it and get back. There is still 1 error according to Jigsaw;

```
#SimpleRedirects input[type=checkbox] {
    margin: 4px 0 0;
    margin-top: 1px \9; // ERROR
    line-height: normal;
}

```

I will try to remove this line if it still doesn't work. In the meantime, just out of curiousity, can you explain the meaning of the line?

**Comment by patrickdemooij9** [comment]
> > version 3.1.0 (Umbraco v10)
> 
> Thank you. I will try it and get back. There is still 1 error according to Jigsaw;
> 
> ```
> #SimpleRedirects input[type=checkbox] {
>     margin: 4px 0 0;
>     margin-top: 1px \9; // ERROR
>     line-height: normal;
> }
> ```
> 
> I will try to remove this line if it still doesn't work. In the meantime, just out of curiousity, can you explain the meaning of the line?

That is indeed not valid CSS. I must have totally missed that. The \9 shouldn't be there

**Comment by kdx-perbol** [comment]
> That is indeed not valid CSS. I must have totally missed that. The \9 shouldn't be there

**3.1.0 works** even with that line. I can see in the rendered backoffice CSS that the `\9` is copied verbatim by Smidge/Nuglify. 

Thanks!

I guess it will remain a mystery why 3.0 has worked for others.

**Comment by patrickdemooij9** [comment]
> **3.1.0 works** even with that line. I can see in the rendered backoffice CSS that the `\9` is copied verbatim by Smidge/Nuglify.
> 
> Thanks!
> 
> I guess it will remain a mystery why 3.0 has worked for others.

Great to hear! Also created an issue for the `\9` here https://github.com/patrickdemooij9/SimpleRedirects/issues/27, but luckily that doesn't block you from using the package now
