### ISSUE TITLE
Option to ignore query strings in redirects

### ISSUE THREAD

**Issue by b3023630** [patrickdemooij9/SimpleRedirects#29]
Hi,

I'm using SimpleRedirects 2.1.0 on Umbraco 9.5.4 and we need the redirects to work on URLs with query strings as well i.e.
xyz.com/test-page -> xyz.com/new-page works fine but xyz.com/test-page?myparam=true does not.

I noticed an old, closed issue where this was addressed in an older version:
https://github.com/patrickdemooij9/SimpleRedirects/issues/18

I have tried to add SimpleRedirects.IgnoreQueryString to the web.config and the same values to the appsettings.json, but this does not seem to work. Am I missing something? Or does this functionality not exist in this version of the package?
If it doesn't exist, is this something that can be added?

**Comment by patrickdemooij9** [comment]
Hi @b3023630 
The functionality that you are talking about is indeed not present on 2.1.0 as Umbraco 9 will be end of life at the end of next month, so it was not expecting someone to still be on that version.
I can take a look at adding the functionality to the Umbraco 9 version if you aren't planning on upgrading to Umbraco 10 in the coming future.

**Comment by b3023630** [comment]
Unfortunately, upgrading Umbraco is up to the client and not myself, so can't see it happening anytime soon.

If this is something you could add in, that would be amazing!

**Comment by patrickdemooij9** [comment]
Hi @b3023630 
This feature has now been added to the 2.3.0 version of SimpleRedirects. (https://github.com/patrickdemooij9/SimpleRedirects/releases/tag/release%2F2.3.0).
