### ISSUE TITLE
Handling Redirects for URL's with File Extensions

### ISSUE THREAD

**Issue by StuartPaterson** [patrickdemooij9/SimpleRedirects#32]
Hi Patrick,

We're looking to add redirects for url's with file extensions, for example as we've moved from serving a pdf on completion of a form to an online brochure link but would like to redirect clicks on the legacy pdf brochures to another page.

We've tried adding them through Simple Redirects but they come up as invalid, is that something on the road map or is there a key I'm maybe missing to enable that feature/functionality?

We're currently on Umbraco 8.18 at the moment with v1.0.11-beta1 of Simple Redirects, this was the package you created for us last year to retain query strings.

Thanks,
Stuart

**Comment by patrickdemooij9** [comment]
Hi Stuart,

It is correct that SimpleRedirects doesn't redirect files. The newer versions for Umbraco 9+ do support file redirects, but this is unfortunately not an easy thing to do with Umbraco 8.

**Comment by StuartPaterson** [comment]
Hi Patrick,

Thanks for confirming, I'll close this off then as we do have Umbraco upgrades scheduled for this year so we'll get the Simple Redirects functionality when that's done.

Thanks,
Stuart
