### ISSUE TITLE
Install didn't work

### ISSUE THREAD

**Issue by brightspectrum-da-bomb** [patrickdemooij9/SimpleRedirects#8]
I tried installing the package through the backoffice and again via NuGet package and neither seems to have worked. I don't see any new options in the Content section or changes to my web.config file. 

Umbraco version 8.9.0

**Comment by patrickdemooij9** [comment]
Hey @brightspectrum-da-bomb,

Sorry for the late response, I don't remember seeing a notification. I'll look into this!

**Comment by patrickdemooij9** [comment]
Hi @brightspectrum-da-bomb,

I just tried a fresh installation of Umbraco 8.9.0 and added the package to it and it seems to work fine for me. Are you sure that you are using the SimpleRedirects package and not the Simple301 package?
The redirects should be listed here:
![image](https://user-images.githubusercontent.com/11466511/100381953-7aa74e80-301a-11eb-9c66-41874d3620f5.png)

Let me know if this helps you!
