### ISSUE TITLE
Preserving querystring

### ISSUE THREAD

**Issue by McGern** [patrickdemooij9/SimpleRedirects#9]
Hi,

Does this package work with preserving querystring? I'm getting inconsistent results, like sometimes it appears to be working, and other times it doesn't, and it's giving 404's when there are multiple redirects involved.

Thanks,
J

**Comment by patrickdemooij9** [comment]
Hey McGern,

Currently, it does not preserve query strings. However, this is something that I can add to the package. And could you tell me what redirects you have that are giving you 404's? That shouldn't happen.

Thanks,
Patrick

**Comment by McGern** [comment]
Hi Patrick,

Was getting 404s when a redirected url with a querystring was pointing to one of the redirects in the "redirects" section in umbraco. This is an example of what I was seeing

redirect in umbraco for page change
/page1 => /page2

Simple Redirects has
/old-page => /page1

If you didn't have a querystring then the redirect works, when I had a querystring it didn't redirect at all.

Sorry, don't have an example anymore because we swapped out the redirect manager.

Thanks,
Jarrod
